title: Nuggets
timezone: Europe/Dublin
description: >-
  A collection of small nuggets of information.
url: "https://nuggets.otormaigh.ie"
github_username:  otormaigh
permalink: /:title

plugins:
  - jekyll-feed
